CREATE SCHEMA IF NOT EXISTS tdd;


CREATE TABLE IF NOT EXISTS tdd.CUSTOMERS (
    CUSTOMER_ID  UUID PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR UNIQUE,
    PHONE VARCHAR,
    ADDRESS VARCHAR
);
